/*ESTUDIANTE: Jose Megun Cama La Madrid */

/*Creacion de table persona*/
CREATE TABLE gamarket.persona
(
   IDPER INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 200 INCREMENT BY 1,
   DNIPER CHAR(8),
   NOMPER VARCHAR2(60),
   APEPER VARCHAR2(80),
   EMAPER VARCHAR2(80),
   CELPER CHAR(9),
   TIPPER CHAR(1) CHECK (TIPPER IN ('V', 'C')),
   ESTPER CHAR(1) DEFAULT 'A' CHECK (ESTPER IN ('A', 'I')),
   FECNACPER DATE,
   CONSTRAINT PER_PK PRIMARY KEY (IDPER)
);
COMMIT;

/*Creando la tabla venta*/
CREATE TABLE gamarket.venta(
   IDVEN INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
   FECVEN DATE,
   IDVEND INT,
   IDCLI INT,
   TIPPAGVEN CHAR(1),
   ESTVEN CHAR(1) DEFAULT 'A',
   CONSTRAINT VEN_PK PRIMARY KEY (IDVEN)
);
COMMIT;

/*Creando la tabla Venta-detalle */
CREATE TABLE gamarket.venta_detalle(
    IDVENDET INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 300 INCREMENT BY 1,
    IDVEN INT,
    CODPROD CHAR(3),
    CANVENDET INT,
    CONSTRAINT VENDET_PK PRIMARY KEY (IDVENDET)
);
COMMIT;

/*Creando la tabla producto */
CREATE TABLE gamarket.producto(
    CODPROD CHAR(3),
    NOMPRO VARCHAR2(50),
    PREPRO NUMBER(8,2),
    STOCKPRO INT,
    IDCATPRO INT,
    ESTPRO CHAR(1) DEFAULT 'A',
    CONSTRAINT PROD_PK PRIMARY KEY (CODPROD)
);
COMMIT;

/*Creando la tabla categoria */
CREATE TABLE gamarket.categoria(
    IDCAT INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 10 INCREMENT BY 10,
    NOMCAT VARCHAR2(60),
    CONSTRAINT CAT_PK PRIMARY KEY (IDCAT)
);
COMMIT;

/*Listar tablas: */
SELECT table_name FROM all_tables WHERE owner = 'GAMARKET' ORDER BY table_name;

/*RELACIONES: */
-- Relacionar tabla VENTA (VENDEDOR) - PERSONA
ALTER TABLE gamarket.venta
    ADD CONSTRAINT FK_VENTA_PERSONA
    FOREIGN KEY (IDVEND)
    REFERENCES gamarket.persona(IDPER);
COMMIT;

-- Relacionar tabla VENTA (CLIENTE) - PERSONA
ALTER TABLE gamarket.venta
    ADD CONSTRAINT FK_VENTA_CLIENTE
    FOREIGN KEY (IDCLI)
    REFERENCES gamarket.persona(IDPER);
COMMIT;

-- Relacionar tabla venta-detallte - venta
ALTER TABLE gamarket.venta_detalle
    ADD CONSTRAINT FK_VENTA_DETALLE_VENTA
    FOREIGN KEY (IDVEN)
    REFERENCES gamarket.venta(IDVEN);
COMMIT;

-- Relacionar tabla venta_detalle - producto
ALTER TABLE gamarket.venta_detalle
    ADD CONSTRAINT FK_VENTA_DETALLE_PRODUCTO
    FOREIGN KEY (CODPROD)
    REFERENCES gamarket.producto(CODPROD);
COMMIT;

-- Relacionar tabla producto - CATEGORIA
ALTER TABLE gamarket.producto
    ADD CONSTRAINT FK_PRODUCTO_CATEGORIA
    FOREIGN KEY (IDCATPRO)
    REFERENCES gamarket.categoria(IDCAT);
COMMIT;

/* Listar relaciones de la tabla VENTA */
SELECT 
   table_name, 
   constraint_name, 
   constraint_type, 
   r_owner, 
   r_constraint_name 
FROM all_constraints 
WHERE owner = 'GAMARKET';